# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main

pool: TKS-AGENT

stages:
- stage: Terraform_init_validate
  displayName: 'Terraform init and validate'

  jobs:
  - job: Init_Validate
    displayName: 'Init and validate'

    steps:
    - task: TerraformInstaller@1
      displayName: 'Terraform Installation'
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'
        backendAzureRmUseEntraIdForAuthentication: false
        backendServiceArm: 'aks-svc'
        backendAzureRmResourceGroupName: 'rg-bknd'
        backendAzureRmStorageAccountName: 'stgbknd'
        backendAzureRmContainerName: 'bkndcrn'
        backendAzureRmKey: 'dev.tfstate'

    - task: TerraformTask@5
      displayName: 'Terraform validate'
      inputs:
        provider: 'azurerm'
        command: 'validate'
        workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'

    
- stage: Terraform_security_scan
  displayName: 'Install Checkov'
  dependsOn: Terraform_init_validate
  condition: succeeded()

  jobs:
  - job: security_scan
    displayName: 'Ceckov security scan'

    steps:
    - task: trivy@2
      inputs:
        version: 'latest'
        type: 'filesystem'
        target: '$(System.DefaultWorkingDirectory)/env/dev'
        ignoreScanErrors: true
    



- stage: Terraform_Plan
  displayName: 'Terraform Plan'
  dependsOn: Terraform_init_validate
  condition: succeeded()

  jobs: 
  - job: Plan
    displayName: 'Terraform Plan'
    
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'

    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'
        backendAzureRmUseEntraIdForAuthentication: false
        backendServiceArm: 'aks-svc'
        backendAzureRmResourceGroupName: 'rg-bknd'
        backendAzureRmStorageAccountName: 'stgbknd'
        backendAzureRmContainerName: 'bkndcrn'
        backendAzureRmKey: 'dev.tfstate'
    - task: TerraformTask@5
      displayName: 'Terraform Plan'
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'
        environmentServiceNameAzureRM: 'aks-svc'

    


- stage: Terraform_apply
  displayName: 'Terraform apply'
  dependsOn: Terraform_Plan
  condition: succeeded()

  jobs:
  - job: Apply
    displayName: 'Terraform Apply'

    steps:

    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'
        backendAzureRmUseEntraIdForAuthentication: false
        backendServiceArm: 'aks-svc'
        backendAzureRmResourceGroupName: 'rg-bknd'
        backendAzureRmStorageAccountName: 'stgbknd'
        backendAzureRmContainerName: 'bkndcrn'
        backendAzureRmKey: 'dev.tfstate'

    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'
        commandOptions: '-auto-approve'
        environmentServiceNameAzureRM: 'aks-svc'

    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'destroy'
        workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'
        commandOptions: '-auto-approve'
        environmentServiceNameAzureRM: 'aks-svc'